### PR TITLE
feat: Add warning to transfer modal

### LINKED ISSUE #1109: Add warning before KSM transfer
### Detailed Description

It is possible to transfer KSM from the Basilisk UI to any BSX address, including exchanges. 
We have had reports of users sending their KSM from Basilisk network to CEXs, resulting in loss of funds.

We should add a warning when doing a transfer in the Basilisk UI to not send KSM directly to exchanges.

### Possible Implementation

" **All assets are on Basilisk Network.** Please do not use this interface for transferring any assets to CEX - with the exception of BSX "

image
Warning somewhere here

image
Directly under transfer

image
Same style as existing warnings, but using an amber colour

image
Maybe E5B30B

### PR DESCRIPTION
**Pull request by Matehoo**
fixes #1109 
Screenshot 2022-09-23 at 11 28 20

### CODE REVIEW

**Comment by jak-pan** [comment]
This doesn't make any sense since you can't transfer assets anywhere else from this screen now and the bx rule is not valid since you can do to any other address

**Comment by jak-pan** [comment]
cc @lolmcshizz what was the thing you wanted to do here?

**Comment by lolmcshizz** [comment]
@jak-pan we need a warning to make users think twice before transferring KSM directly from Basilisk UI to a CEX - they are losing funds. See discussion in #ui this morning.

**Comment by jak-pan** [comment]
Okay so the error should state when transferring other than basilisk token to other than basilisk address that you should not send tokens to CEX address or you will lose your funds. (probably just temporarily locked out of until they manage it)

**Comment by Matehoo** [comment]
@jak-pan so current proposed solution is:

- create mechanism for checking if you try to send bridged assets and if outside of bsx chain (bX address)
- change warning text to warn only in appropriate cases, exact wording tbd
- show warning only when transferring bridged assets outside of bsx chain

**Comment by jak-pan** [comment]
We are never sending assets outside of our chain in the current UI so it would appear only when non-bx address is used. (I would reuse the wallet selection style of showing address if possible)

**Pull request closed without merging**
